baseURL: "https://www.minimaximum.gr/"
relativeURLs: false
canonifyURLs: false
config: "config.yaml"
defaultLayout: "single"
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false
disableLiveReload: false
enableGitInfo: false
disableHugoGeneratorInject: true
# Allows you to disable all page types and will render nothing related to 'kind';
# values = "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"
disableKinds: ["RSS", "sitemap", "robotsTXT", "404"]
enableMissingTranslationPlaceholders: false
googleAnalytics: ""
languages:
    en:
        weight: 1
        languageName : "English"
    el:
        weight: 2
        languageName : "Ελληνικά"
summaryLength: 70
metaDataFormat: "yaml"
paginate: 10
paginatePath: "page"
pluralizeListTitles: false
preserveTaxonomyNames: false
publishDir: "public"
staticDir: "static"
themesDir: "themes"
theme: ""
title: "MiniMaximum improVision"
titleCaseStyle: "AP"
uglyURLs: false
verbose: true
watch: true
description: "Minimaximum Improvision is an improvisational group of musicians, architects and visual artists that work on narrative concepts, using acoustic and electric instruments, sampled sounds, voices, texts, objects and images."
